name: github_api
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.6

dependencies:
    http: ^1.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.25.2
  mocktail: ^1.0.3
