name: committer
description: "An app to analize Github commits"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.2.0
  flutter_lints: ^2.0.0
  test: ^1.25.2
  bloc_test: ^9.1.5
  mocktail: ^1.0.3
  webview_flutter: ^4.5.0

  github_repository:
    path: packages/github_repository

  github_api:
    path: packages/github_api

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
