name: github_repository
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.6

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.1.0
  test: ^1.25.2
